### ISSUE TITLE
calcChessboardCorners所产生的点的位置与findChessboardCorners检测到的角点排序不需要一一对应么

### ISSUE THREAD

**Issue by mmchen88** [zhanxiage1994/binocularDistance#2]
calcChessboardCorners所产生的点的位置由左上角依次排序到右下角，而findChessboardCorners检测到的角点由右下角依次排序至左上角，二者并非一一对应。

**Comment by zhanxiage1994** [comment]
需要对应一下，你说的这个问题可能和版本有关吧
